name: Deploy to EC2

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/note/note-back
            git fetch origin dev
            git reset --hard origin/dev
            git pull origin dev --force
            ./gradlew build
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/note-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
